site:
  title: Cluster-API
  url: /
  start_page: main@turtles-documentation::index.adoc

content:
  sources:
    - url: ./
      branches: [main]

# Description: SUSE UI bundle
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site